.TH "dsr::Argument_helper::FlagTarget" 3 "Wed Jan 4 2012" "ArgumentHelper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsr::Argument_helper::FlagTarget \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdsr::Argument_helper::Argument_target\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlagTarget\fP (char k, const char *lname, const char *descr, bool &b)"
.br
.ti -1c
.RI "virtual bool \fBprocess\fP (int &, const char **&)"
.br
.ti -1c
.RI "virtual void \fBwrite_value\fP (std::ostream &out) const "
.br
.ti -1c
.RI "virtual void \fBwrite_usage\fP (std::ostream &out) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool & \fBval\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ArgumentHelper from the source code.
